# Generated by Django 6.0.3 on 2026-03-29 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('tel', models.CharField(default='', max_length=255)),
                ('etablissement', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='files/', verbose_name='Picture')),
                ('typecompte', models.CharField(choices=[('professeur', 'Professeur'), ('eleve', 'Elève'), ('staff', 'Staff')], default='professeur', max_length=50)),
                ('note', models.IntegerField(blank=True, null=True)),
                ('npi', models.CharField(blank=True, max_length=255, null=True)),
                ('his_registration_date', models.DateTimeField(auto_now=True)),
                ('his_update_date', models.DateTimeField(auto_now=True)),
                ('his_delete_date', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='date_joined')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MT_Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('f_active', models.BooleanField(default=True)),
                ('his_registration_date', models.DateTimeField(auto_now=True)),
                ('his_update_date', models.DateTimeField(auto_now=True)),
                ('his_delete_date', models.DateTimeField(auto_now=True)),
                ('delete_userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useriddelcom', to=settings.AUTH_USER_MODEL)),
                ('update_userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useridupcom', to=settings.AUTH_USER_MODEL)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useridcom', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comm', to='src.mt_commune'),
        ),
        migrations.CreateModel(
            name='MT_Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('f_active', models.BooleanField(default=True)),
                ('his_registration_date', models.DateTimeField(auto_now=True)),
                ('his_update_date', models.DateTimeField(auto_now=True)),
                ('his_delete_date', models.DateTimeField(auto_now=True)),
                ('delete_userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useriddelmatier', to=settings.AUTH_USER_MODEL)),
                ('update_userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useridupmatier', to=settings.AUTH_USER_MODEL)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useridmatier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matier', to='src.mt_matiere'),
        ),
        migrations.CreateModel(
            name='MT_speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('f_active', models.BooleanField(default=True)),
                ('his_registration_date', models.DateTimeField(auto_now=True)),
                ('his_update_date', models.DateTimeField(auto_now=True)),
                ('his_delete_date', models.DateTimeField(auto_now=True)),
                ('delete_userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useriddelspecia', to=settings.AUTH_USER_MODEL)),
                ('update_userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useridupspecia', to=settings.AUTH_USER_MODEL)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useridspecia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sepecia', to='src.mt_speciality'),
        ),
        migrations.CreateModel(
            name='MT_study_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('f_active', models.BooleanField(default=True)),
                ('his_registration_date', models.DateTimeField(auto_now=True)),
                ('his_update_date', models.DateTimeField(auto_now=True)),
                ('his_delete_date', models.DateTimeField(auto_now=True)),
                ('delete_userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useriddelstudy', to=settings.AUTH_USER_MODEL)),
                ('update_userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useridupstudy', to=settings.AUTH_USER_MODEL)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useridstudylevel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='levelstudy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studylevel', to='src.mt_study_level'),
        ),
    ]
