# Generated by Django 6.0.3 on 2026-03-29 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DT_Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_fullname', models.CharField(default='', max_length=255)),
                ('student_birthday', models.DateField(blank=True, null=True)),
                ('student_tel', models.CharField(default='', max_length=255)),
                ('student_etablissement', models.CharField(blank=True, max_length=255, null=True)),
                ('student_gender', models.CharField(blank=True, max_length=255, null=True)),
                ('student_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('type_call', models.CharField(blank=True, max_length=255, null=True)),
                ('f_active', models.BooleanField(default=True)),
                ('his_registration_date', models.DateTimeField(auto_now=True)),
                ('his_update_date', models.DateTimeField(auto_now=True)),
                ('his_delete_date', models.DateTimeField(auto_now=True)),
                ('delete_userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useriddelcall', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stdmatier', to='src.mt_matiere')),
                ('student_commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stdcomm', to='src.mt_commune')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useridteacher', to=settings.AUTH_USER_MODEL)),
                ('update_userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useridupcall', to=settings.AUTH_USER_MODEL)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useridcall', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
